CREATE TABLE `Employees` (
  `Emp_ID` varchar(10) DEFAULT NULL,
  `First_Name` varchar(10) DEFAULT NULL,
  `Last_Name` varchar(10) DEFAULT NULL,
  `Gender` varchar(10) DEFAULT NULL,
  `Country` varchar(15) DEFAULT NULL,
  `City` varchar(25) DEFAULT NULL,
  `Designation` varchar(25) DEFAULT NULL,
  `Department` varchar(25) DEFAULT NULL,
  `Age` int DEFAULT NULL
);

INSERT INTO `Employees` (`Emp_ID`, `First_Name`, `Last_Name`, `Gender`, `Country`, `City`, `Designation`, `Department`, `Age`) VALUES
('E00254', 'Emily', 'Alexander', 'Female', 'United States', 'Houston', 'Sr. Manger', 'IT', 55),
('E02166', 'Luna', 'Jackson', 'Female', 'United States', 'Denver', 'Director', 'Sales', 43),
('E00935', 'Penelope', 'Pena', 'Female', 'United States', 'Portland', 'Computer Systems Manager', 'Human Resources', 31),
('E01525', 'Adrian ', 'Ruiz', 'Male', 'Brazil', 'Manaus', 'Sr. Manger', 'Sales', 56),
('E00386', 'Joshua ', 'Juarez', 'Male', 'Brazil', 'Rio de Janerio', 'Director', 'IT', 59),
('E03383', 'Everett ', 'Morales', 'Female', 'Brazil', 'Rio de Janerio', 'Quality Engineer', 'Engineering', 56),
('E01258', 'Eva', 'Garcia', 'Male', 'Brazil', 'Manaus', 'Analyst', 'Finance', 65),
('E01225', 'Isabella', 'William', 'Female', 'United States', 'Austin', 'Sr. Analyst', 'Engineering', 34),
('E00388', 'Sadie', 'Coleman', 'Female', 'United States', 'Boston', 'Sr. Manger', 'Marketing', 36),
('E03483', 'Eva', 'Butler', 'Female', 'United States', 'Seattle', 'Controls Engineer', 'Engineering', 27),
('E00530', 'Daniel', 'Perry', 'Male', 'United States', 'Jacksonville', 'Manager', 'Sales', 59),
('E03496', 'Ethan', 'Simmons', 'Male', 'United States', 'Columbus', 'Sr. Analyst', 'Sales', 31),
('E00549', 'Leilani', 'Anthony', 'Female', 'United States', 'Atlanta', 'Vice President', 'Marketing', 47),
('E00163', 'Rylee', 'Yu', 'Female', 'United States', 'Phoenix', 'Director', 'Finance', 32),
('E00884', 'Piper', 'Watson', 'Female', 'United States', 'Seattle', 'Sr. Manger', 'Marketing', 44),
('E04732', 'Zoey', 'Benjamin', 'Female', 'United States', 'Nashville', 'Director', 'Sales', 38),
('E04545', 'Penelope', 'Williams', 'Female', 'Brazil', 'Rio de Janerio', 'Quality Engineer', 'Engineering', 56),
('E01621', 'Jackson ', 'Martin', 'Male', 'United States', 'Phoenix', 'Vice President', 'Marketing', 42),
('E03554', 'John ', 'Moore', 'Male', 'United States', 'Jacksonville', 'Vice President', 'IT', 52),
('E03548', 'Gabriel ', 'Morales', 'Male', 'United States', 'Columbus', 'Enterprise Architect', 'IT', 40),
('E02185', 'Wyatt ', 'Clark', 'Male', 'United States', 'Miami', 'Computer Systems Manager', 'IT', 32),
('E02186', 'Dominic ', 'Ross', 'Male', 'United States', 'Austin', 'Quality Engineer', 'Engineering', 52),
('E02195', 'John ', 'Wang', 'Male', 'United States', 'Chicago', 'Analyst II', 'Marketing', 35),
('E02199', 'Christian ', 'Sanders', 'Male', 'United States', 'Miami', 'Vice President', 'Human Resources', 48),
('E02966', 'William ', 'Foster', 'Male', 'United States', 'Sacramento', 'Field Engineer', 'Engineering', 58),
('E00665', 'David ', 'Rogers', 'Male', 'United States', 'Seattle', 'Controls Engineer', 'Engineering', 55),
('E00791', 'Thomas ', 'Padilla', 'Male', 'Brazil', 'Sao Paulo', 'Vice President', 'Marketing', 57),
('E01540', 'Miles ', 'Marquez', 'Male', 'Brazil', 'Sao Paulo', 'IT Coordinator', 'IT', 36),
('E00244', 'Samuel ', 'Thomas', 'Male', 'United States', 'Phoenix', 'Analyst II', 'Finance', 34),
('E00230', 'John ', 'Clark', 'Male', 'United States', 'Phoenix', 'Sr. Manger', 'Finance', 60),
('E03446', 'Joseph ', 'Martin', 'Male', 'United States', 'Louisville', 'Analyst II', 'Marketing', 41),
('E00529', 'Jose ', 'Alvarado', 'Male', 'United States', 'Boston', 'Engineering Manager', 'Engineering', 40),
('E00214', 'Parker ', 'Holmes', 'Male', 'United States', 'Austin', 'Quality Engineer', 'Engineering', 45),
('E00984', 'Lincoln ', 'Reed', 'Male', 'United States', 'Chicago', 'Director', 'Accounting', 41),
('E04712', 'Gabriel', 'Contreras', 'Male', 'United States', 'Boston', 'Network Engineer', 'IT', 29),
('E04713', 'Gabriel', 'Skantze', 'Male', 'United States', 'Houston', 'Network Engineer', 'IT', 32);
COMMIT;