-- 1. Show sales generated by employees ordered from highest to lowest
SELECT 
    e.first_name, 
    e.last_name, 
    e.country, 
    s1.segment, 
    s1.product, 
    s1.Sales, 
    ROW_NUMBER() OVER (ORDER BY s1.Sales DESC) AS RowNumber
FROM 
    Employees e 
INNER JOIN 
    Sales s1 
ON 
    e.EMP_ID = s1.EMPID;

-- 2. Show ranked sales per employee by segment
SELECT 
    e.first_name, 
    e.last_name, 
    s1.product, 
    s1.segment, 
    s1.Sales, 
    RANK() OVER (PARTITION BY e.last_name ORDER BY s1.Sales DESC) AS sales_rank
FROM 
    Employees e 
INNER JOIN 
    Sales s1 
ON 
    e.EMP_ID = s1.EMPID
ORDER BY 
    e.last_name, 
    sales_rank;

SELECT COALESCE(middle_name, 'N/A') AS MidName FROM Employees;
